/// Flutter icons Weather
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Weather
///      fonts:
///       - asset: fonts/Weather.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
///
import 'package:flutter/widgets.dart';

class WeatherIcon {
  WeatherIcon._();

  static const _kFontFam = 'WeatherIcon';

  static const IconData compass = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData close_circle = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData qingtian = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData duoyunzhuanqing = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData qingzhuanduoyun = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData yintian = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData xiaoyu = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData zhongyu = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData dayu = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData baoyu = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData leiyu = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData zhenyu = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData leizhenyu = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData xiaoxue = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData zhongxue = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData daxue = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData baoxue = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData yujiaxue = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData bingbao = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData feng = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData shachengbao = const IconData(0xe814, fontFamily: _kFontFam);
  static const IconData shachengbao1 = const IconData(0xe815, fontFamily: _kFontFam);
  static const IconData youwu = const IconData(0xe816, fontFamily: _kFontFam);
  static const IconData baitianyoufeng = const IconData(0xe817, fontFamily: _kFontFam);
  static const IconData baitianyangsha = const IconData(0xe818, fontFamily: _kFontFam);
  static const IconData taiyangshengqi = const IconData(0xe819, fontFamily: _kFontFam);
  static const IconData taiyangxiala = const IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData yewan = const IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData yejianduoyun = const IconData(0xe81c, fontFamily: _kFontFam);
  static const IconData yejianyouyu = const IconData(0xe81d, fontFamily: _kFontFam);
  static const IconData yejianyouxue = const IconData(0xe81e, fontFamily: _kFontFam);
  static const IconData yejianzhenyu = const IconData(0xe81f, fontFamily: _kFontFam);
  static const IconData message = const IconData(0xe828, fontFamily: _kFontFam);
  static const IconData shaixuan_o = const IconData(0xeb4c, fontFamily: _kFontFam);
  static const IconData tupian_o = const IconData(0xeb4f, fontFamily: _kFontFam);
  static const IconData weixiufuwu_o = const IconData(0xeb5c, fontFamily: _kFontFam);
  static const IconData jiqiren_o = const IconData(0xeb62, fontFamily: _kFontFam);
  static const IconData lianjie_o = const IconData(0xeb65, fontFamily: _kFontFam);
  static const IconData quxiaolianjie_o = const IconData(0xeb67, fontFamily: _kFontFam);
  static const IconData yinliang_o = const IconData(0xeb6b, fontFamily: _kFontFam);
  static const IconData yuyin_o = const IconData(0xeb6c, fontFamily: _kFontFam);
  static const IconData zanting_o = const IconData(0xeb6d, fontFamily: _kFontFam);
  static const IconData zhuti_tiaosepan_o = const IconData(0xeb6e, fontFamily: _kFontFam);
  static const IconData anquan_o = const IconData(0xeb71, fontFamily: _kFontFam);
  static const IconData caidan_o = const IconData(0xeb72, fontFamily: _kFontFam);
  static const IconData chexiao_o = const IconData(0xeb73, fontFamily: _kFontFam);
  static const IconData duihao_o = const IconData(0xeb75, fontFamily: _kFontFam);
  static const IconData Androidgengduo_o = const IconData(0xeb76, fontFamily: _kFontFam);
  static const IconData guanbi_o = const IconData(0xeb77, fontFamily: _kFontFam);
  static const IconData guanyu_o = const IconData(0xeb78, fontFamily: _kFontFam);
  static const IconData jiahao_o = const IconData(0xeb79, fontFamily: _kFontFam);
  static const IconData jiazai_shuang_o = const IconData(0xeb7a, fontFamily: _kFontFam);
  static const IconData jiazai_shuaxin_o = const IconData(0xeb7b, fontFamily: _kFontFam);
  static const IconData linggan_o = const IconData(0xeb7d, fontFamily: _kFontFam);
  static const IconData xiangji_o = const IconData(0xeb86, fontFamily: _kFontFam);
  static const IconData iosgengduo_o = const IconData(0xeb87, fontFamily: _kFontFam);
  static const IconData icon_add = const IconData(0xeb8f, fontFamily: _kFontFam);
  static const IconData icon_compile = const IconData(0xeb93, fontFamily: _kFontFam);
  static const IconData icon_GPS = const IconData(0xeb95, fontFamily: _kFontFam);
  static const IconData icon_horn = const IconData(0xeb96, fontFamily: _kFontFam);
  static const IconData icon_index_line = const IconData(0xeb97, fontFamily: _kFontFam);
  static const IconData icon_link = const IconData(0xeb98, fontFamily: _kFontFam);
  static const IconData icon_im_voice = const IconData(0xeb99, fontFamily: _kFontFam);
  static const IconData icon_message = const IconData(0xeb9a, fontFamily: _kFontFam);
  static const IconData icon_more = const IconData(0xeb9b, fontFamily: _kFontFam);
  static const IconData icon_notice = const IconData(0xeb9c, fontFamily: _kFontFam);
  static const IconData icon_share = const IconData(0xeb9e, fontFamily: _kFontFam);
  static const IconData icon_warn = const IconData(0xeba1, fontFamily: _kFontFam);
  static const IconData biaoqing_xiao_o = const IconData(0xeba9, fontFamily: _kFontFam);
  static const IconData biaoqing_beishang_o = const IconData(0xebab, fontFamily: _kFontFam);
  static const IconData fenxiang_o = const IconData(0xebac, fontFamily: _kFontFam);
  static const IconData icon_replieslist = const IconData(0xebad, fontFamily: _kFontFam);
  static const IconData xiai_o = const IconData(0xebaf, fontFamily: _kFontFam);
  static const IconData zan_o = const IconData(0xebb0, fontFamily: _kFontFam);
  static const IconData icon_warn_fill = const IconData(0xebb1, fontFamily: _kFontFam);
  static const IconData dengchu_o = const IconData(0xebcc, fontFamily: _kFontFam);
}
